`ifndef RV32IM_MEMORY_PROFILE_VH
`define RV32IM_MEMORY_PROFILE_VH

`include "memory_profile_overrides.vh"

`ifndef RV32IM_IMEM_DEPTH_WORDS
`define RV32IM_IMEM_DEPTH_WORDS 1024
`endif

`ifndef RV32IM_DMEM_DEPTH_WORDS
`define RV32IM_DMEM_DEPTH_WORDS 1024
`endif

`ifndef RV32IM_TB_IMEM_INIT_WORDS
`define RV32IM_TB_IMEM_INIT_WORDS `RV32IM_IMEM_DEPTH_WORDS
`endif

`ifndef RV32IM_TB_DMEM_INIT_WORDS
`define RV32IM_TB_DMEM_INIT_WORDS `RV32IM_DMEM_DEPTH_WORDS
`endif

`endif
